// const fs = require("fs");
// const es = require("event-stream");

// let todayGroupLog = [];
// let startGetLogFlag = true;

// const s = fs
//   .createReadStream("system_check.log")
//   .pipe(es.split())
//   .pipe(
//     es
//       .mapSync(function (line) {
//         // pause the readstream
//         s.pause();

//         // process line here and call s.resume() when ready
//         const d = new Date("2023-11-10");
//         const todayString = `${d.getUTCFullYear()}-${
//           d.getUTCMonth() + 1
//         }-${d.getUTCDate()}`;
//         // console.log(todayString);
//         const groupString = "|====================<>=====================|";
//         if (line.includes("Timestamp") && !line.includes(todayString)) {
//           startGetLogFlag = false;
//           todayGroupLog = [];
//         }
//         if (line.includes(groupString)) {
//           startGetLogFlag = true;
//         }

//         if (startGetLogFlag) todayGroupLog.push(line);

//         // console.log("Line: " + line);

//         // resume the readstream, possibly from a callback
//         s.resume();
//       })
//       .on("error", function (err) {
//         console.log("Error while reading file.", err);
//       })
//       .on("end", function () {
//         console.log("Read entire file.");
//         console.log(todayGroupLog);
//       })
//   );

const { GoogleSpreadsheet } = require("google-spreadsheet");
const { JWT } = require("google-auth-library");
require("dotenv").config();

const serviceAccountEmail = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
const googlePrivateKey = process.env.GOOGLE_PRIVATE_KEY;

const newRow = {
  "Server Up": "TRUE",
  CPU: "Max avg: ~ 15%",
  Memory: "1.30GB / 7.76GB",
  Disk: "89GB / 100GB",
  "idom-backend-app-1 + 2 + 3": "Up 25 hours (app-2: 5 hours)",
  "idom-backend-nginx-1": "Up 5 weeks",
  "idom-backend-redis-1": "Up 5 weeks",
  "idom-frontend-home_app_1": "Up 13 days",
  "idom-frontend-02_app_1": "Up 13 days",
  "idom-frontend-04_app_1": "Up 5 weeks",
  "idom-frontend-07_app_1": "Up 13 days",
  "idom-frontend-08_app_1": "Up 13 days",
  "idom-frontend-lp10_app_1": "Up 13 days",
  Note: "Recorded at 1AM AEST",
};

async function getGoogleSpreadsheet() {
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: serviceAccountEmail,
    key: googlePrivateKey,
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });

  const sheetId = "1Ho5pZUm-pSnCNBlqvM043WKKfxmmFTp8gtRk7o1abfk";

  const doc = new GoogleSpreadsheet(sheetId, serviceAccountAuth);

  await doc.loadInfo(); // loads document properties and worksheets
  const sheet = doc.sheetsByTitle["November"];
  // read rows
  const rows = await sheet.getRows(); // can pass in { limit, offset }
  let index = 0;
  while (rows[index].get("Server Up")) {
    index++;
  }

  rows[index].assign(newRow);
}

getGoogleSpreadsheet();
